// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A5-jY_jxv8M06RFQTNy_3Q2J5VsQx3o',
    appId: '1:954645898333:web:b90f0440cdb0ca2f6e99b4',
    messagingSenderId: '954645898333',
    projectId: 'bookswap-8c34e',
    authDomain: 'bookswap-8c34e.firebaseapp.com',
    storageBucket: 'bookswap-8c34e.firebasestorage.app',
    measurementId: 'G-PWH31R027Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ePGi8M7S_zOPG2sFeXhwj3FD_yYVgvY',
    appId: '1:954645898333:android:f8d19d8a8b282efe6e99b4',
    messagingSenderId: '954645898333',
    projectId: 'bookswap-8c34e',
    storageBucket: 'bookswap-8c34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKZMPRUHLWL7dyexQUZ4rfwDPF5DfFgvU',
    appId: '1:954645898333:ios:5770ba57c16ef1ed6e99b4',
    messagingSenderId: '954645898333',
    projectId: 'bookswap-8c34e',
    storageBucket: 'bookswap-8c34e.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZMPRUHLWL7dyexQUZ4rfwDPF5DfFgvU',
    appId: '1:954645898333:ios:5770ba57c16ef1ed6e99b4',
    messagingSenderId: '954645898333',
    projectId: 'bookswap-8c34e',
    storageBucket: 'bookswap-8c34e.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_A5-jY_jxv8M06RFQTNy_3Q2J5VsQx3o',
    appId: '1:954645898333:web:b8b9245033d243496e99b4',
    messagingSenderId: '954645898333',
    projectId: 'bookswap-8c34e',
    authDomain: 'bookswap-8c34e.firebaseapp.com',
    storageBucket: 'bookswap-8c34e.firebasestorage.app',
    measurementId: 'G-DK9F17Q56V',
  );
}
